<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="3" total="4" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-07-16T21:33:57 EDT" name="Failed suite [Default Suite]" finished-at="2022-07-16T21:34:06 EDT" duration-ms="8885">
    <groups>
    </groups>
    <test started-at="2022-07-16T21:33:57 EDT" name="tla-tesNG(failed)" finished-at="2022-07-16T21:34:06 EDT" duration-ms="8885">
      <class name="tests.HomeTest">
        <test-method is-config="true" signature="startReporter()[pri:0, instance:tests.HomeTest@49e53c76]" started-at="2022-07-16T21:33:57 EDT" name="startReporter" finished-at="2022-07-16T21:33:57 EDT" duration-ms="450" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReporter -->
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:tests.HomeTest@49e53c76]" started-at="2022-07-16T21:33:57 EDT" name="setUp" finished-at="2022-07-16T21:34:02 EDT" duration-ms="4515" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.HomeTest.test04(java.lang.String) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="localSetUp()[pri:0, instance:tests.HomeTest@49e53c76]" started-at="2022-07-16T21:34:02 EDT" name="localSetUp" finished-at="2022-07-16T21:34:02 EDT" duration-ms="37" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- localSetUp -->
        <test-method signature="test04(java.lang.String)[pri:0, instance:tests.HomeTest@49e53c76]" started-at="2022-07-16T21:34:02 EDT" name="test04" description="Verify the Internet Link takes to the correct page (verify title)" data-provider="homePageLinkTitles" finished-at="2022-07-16T21:34:04 EDT" duration-ms="2301" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[The Internetz]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[pass expected [The Internetz] but found [The Internet]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: pass expected [The Internetz] but found [The Internet]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at tests.HomeTest.test04(HomeTest.java:47)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test04 -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:tests.HomeTest@49e53c76]" started-at="2022-07-16T21:34:04 EDT" name="tearDown" finished-at="2022-07-16T21:34:06 EDT" duration-ms="1958" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test04 status=FAILURE method=HomeTest.test04(java.lang.String)[pri:0, instance:tests.HomeTest@49e53c76] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="endReporter()[pri:0, instance:tests.HomeTest@49e53c76]" started-at="2022-07-16T21:34:06 EDT" name="endReporter" finished-at="2022-07-16T21:34:07 EDT" duration-ms="701" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReporter -->
      </class> <!-- tests.HomeTest -->
    </test> <!-- tla-tesNG(failed) -->
  </suite> <!-- Failed suite [Default Suite] -->
</testng-results>
